spring:
  datasource:
     url: jdbc:mysql://localhost:3306/big_data?useSSL=false
     username: develop
     password: weqCDF@179
     driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
server:
  port: 9008